networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password:
    file: secrets/db_password.txt
  db_root_password:
    file: secrets/db_root_password.txt
  wp_password:
    file: secrets/wp_password.txt

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tviejo/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tviejo/data/wordpress'

services:
  nginx:
    build: requirements/nginx/.
    depends_on:
      wordpress:
        condition: service_healthy
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/html/

  mariadb:
    build: requirements/mariadb/.
    healthcheck:
      test: mysqladmin ping
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    restart: always
    container_name: mariadb
    ports:
      - "3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    secrets:
      - db_password

  wordpress:
    build: requirements/wordpress/.
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: netstat -an | grep 9000 > /dev/null || exit 1
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    restart: always
    container_name: wordpress
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/
    env_file: .env
    secrets:
      - db_password
      - db_root_password
      - wp_password
