version: '3.8'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/thomas/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/thomas/data/wordpress'

services:
  nginx:
    build: requirements/nginx/.
    depends_on:
      wordpress:
        condition: service_healthy
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/

  mariadb:
    build: requirements/mariadb/.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      SQL_DATABASE: ${MYSQL_DATABASE}
      SQL_USER: ${MYSQL_USER}
      SQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build: requirements/wordpress/.
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "netstat", "-an", "|", "grep", "9000"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    restart: always
    container_name: wordpress
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/
    environment:
      SQL_DATABASE: ${MYSQL_DATABASE}
      SQL_USER: ${MYSQL_USER}
      SQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    env_file: .env
